[versions]
# libraries
kotlin = "2.3.10"
# plugins
sollecitom-gradle-plugins = "1.0.0-SNAPSHOT"
palantir-git-plugin = "4.3.0"

[libraries]
sollecitom-gradle-plugins-base = { module = "sollecitom.gradle-plugins:base", version.ref = "sollecitom-gradle-plugins" }
sollecitom-gradle-plugins-kotlin-jvm = { module = "sollecitom.gradle-plugins:kotlin-jvm", version.ref = "sollecitom-gradle-plugins" }

[plugins]
com-palantir-git-version = { id = "com.palantir.git-version", version.ref = "palantir-git-plugin" }
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
